language: java
jdk: oraclejdk8
before_install: echo "sauce.user=$SAUCE_USER" > local.properties && echo "sauce.sauceAccessKey=$SAUCE_ACCESSKEY" >> local.properties
after_success: "./.travis.after_success.sh"
dist: trusty
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/com/vaadin/flow/component
env:
  global:
  - secure: Dyyn5b6ldj5LdCcZhLNt7S1CgYxu3qtCufOZBhYHwojALZAs+aHWHK8EsD2cVgbYYoPQQm0/nLKDTS2qornFBbpFvimAxdXmCjWx7nFVA1NTIUaxdNT8S1ol6xY9IdRr2vc//mdsKAWYdt5bwuThEsbUuT4zWzM6JPpAXxZIgzEcQJ45+8e8rH1onsLNi1Njz8PNdyN4cjYXHDg9wGU0YDA7ng1OoB9h32DqhDsB5yV53D/dAsYXWoJTu28aLgyXE3rcYmboK3U26rh3QqjZ/FK66B+b0yy0mclXu7y2laFNfCEJ5F1MrmhNiZCu/RByJBr4n/JcwxtEOoW/WWR2k2IV9e/jZ76GplWLAESoF7MKZ6hwzPzMGx9TuYxx6I8o53xB2qY7hM9XiDUmbovetAepXy7BOeI27preHjzYQ69NloDJVQ/EYICsZulZZj/Y22NqTKjcHs6COGv2HiVO5MXBvC24XO3lnxQ5//TDR//BAXxKmus1NZYmz/00zSoUPDaLVFG6Yd7lgK2SSoaQYeKxWgn/tEnjhkdUEd3BVtWgiAspLsOITMKGCgnnrfsuzoI2/hnxDr+1u2Wo7rtPlsKQXl9KNWjnmTXq2efdIwTXK0f6YGmSRecAcbnTdaR96PMtnjA70seQg6EnIIRW/gU+Hib2TcvYKrSpsgZ+Y08=
  - secure: vE4oLJYxgdDJTQfCHrsio0xmdeHmfVpfBKNltNf1jXDjzlSTJSyn8CMs6YIk/v0yRBgiKcIq6EO7YWjKsf6dUI1nQVcstXMcEgLGexyAXNju/Zcu3bxZ02/UAWCiOlwpp+9tISwwaanAg5iMc5kAP1Gj/fHvFQbJrH4FVkRNg8kAQ1T7hnYoLHRUo6TdCy+Hr3UkKTldrD0/jDVqcN29nivyKQLvlLDC4WRheGQh+1R7JMLQipL6JzolNMsMsceRnfGZ8jsBmUZ8FSvs0iRRQS2DQYgnWvE5BqKvBkd7i1c//+mzJZugfQwOb7vq+P2H1iO2K1LaHuV657Fr55qdGcosLjMeLMuV35ZVSPnvfFxOx7lN70V57MypjO3Ja/mlYZWB87AkrzvM2ZJabxe3v1n2te1y4tlYWWT9VvwmRcrsuOmKvbKPM2Ly8RF3GURxGa7RpOowmNW2RRgdj3iHrAUs/xxxOAzPAEXsA/3LVRaMsgq/j3lm9ekwakMM/1R5z5mOvRInzvnWxBrZ9IJXIgDYdXARGdsK5tTogVzDbParivCz3X/fyrd6LiIbaxCZ/QEQ0idgl7ufkwQ0ruGf+cUeJuFoAPWL8MeHKLkmWzn6rq9rCj+9c6eWfJUsouXXVjG0clR8vbOGAo7P6CF95BA2N0+FCjEWDGHPWxcHrFM=
